import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';

import { gitlabmono, incognito, ttNorms } from '@/app/assets/font/font';
import ClientLayout from './ClientLayout';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <Head>
            <link rel="icon" href="/src/app/favicon.ico" type="image/x-icon" />
         </Head>
         <body
            className={`${incognito.variable} ${inter.className} ${gitlabmono.variable} ${ttNorms.variable} font-tt-norms dark:bg-zinc-900 bg-white dark:text-white text-dark`}
         >
            <ClientLayout>{children}</ClientLayout>
         </body>
      </html>
   );
}
